apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mypod
  name: hello
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mypod
  template:
    metadata:
      labels:
        app: mypod
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
           claimName: task-pv-claim
      containers:
      - image: adityapratapbhuyan/aditya-test:demo-config1
        name: hello
        env:
         - name: NAME
           valueFrom:
            secretKeyRef:
             name: mysecret1
             key: username
         - name: PASSWORD
           valueFrom:
            secretKeyRef:
             name: mysecret1
             key: password
         - name: LOGFILE
           valueFrom:
            configMapKeyRef:
             name: logconfig
             key: logfile              
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/usr/share/local"
          name: task-pv-storage
      restartPolicy: Always