apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  volumes:
    - name: sec-vol
      secret:
        secretName: secret1   
  containers:
  - args:
    - sleep
    - "9999"
    image: bash
    name: pod1
    resources: {}
    envFrom:
      - configMapRef:
          name: drink1
    volumeMounts:
      - name: sec-vol
        mountPath: /tmp/secret1       
  dnsPolicy: ClusterFirst
  restartPolicy: Never