apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mycj
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: mycj
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from Kubernetes cluster
            image: busybox
            name: mycj
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
