apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello1
  name: hello1
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: hello1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
