apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello
  name: hello
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: hello2
    ports:
    - containerPort: 4600
  - command:
    - /bin/sh
    - -c
    - echo hello;sleep 3600
    image: busybox
    name: hello1
    ports:
    - containerPort: 4500
