apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:
  - name: myapp-container1
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    ports:
    - containerPort: 3000
  - name: myapp-container2
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
    ports:
    - containerPort: 3000
