kind: Pod
apiVersion: v1
metadata:
  labels:
    name: mypvc-pod
  name: mypvc-pod
spec:
   volumes:
   - name: my-volume
     persistentVolumeClaim:
        claimName: mypvc
   containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 80
         name : http-server
      volumeMounts:
      - name: my-volume
        mountPath: /mnt/dbdata
