apiVersion: v1
kind: Pod
metadata:
  name: security-context-container
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: sec-ctx-ctr-pod
    image: gcr.io/google-samples/node-hello:1.0
    ports:
    - containerPort: 9080
      hostPort: 9000
  - name: sec-ctx-ctr
    image: gcr.io/google-samples/node-hello:1.0
    ports:
    - containerPort: 8080
      hostPort: 9500
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false