kind: Pod
apiVersion: v1
metadata:
  name: redis
  labels:
     type: cache-db
spec:
  containers:
  - name: redis-db
    image: redis
    volumeMounts:
    - name: redis-storage
      mountPath: /data/redis
  volumes:
  - name: redis-storage
    emptyDir: {}
